# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: noteManagement.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14noteManagement.proto\"\x1b\n\x0bTypeMessage\x12\x0c\n\x04type\x18\x01 \x01(\x05\"\x1b\n\x08MsgReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1c\n\x08NumChair\x12\x10\n\x08numChair\x18\x01 \x01(\x05\"%\n\x05\x43urso\x12\x0e\n\x06\x63odigo\x18\x01 \x01(\x05\x12\x0c\n\x04nome\x18\x02 \x01(\t\"P\n\nDisciplina\x12\x0e\n\x06\x63odigo\x18\x01 \x01(\t\x12\x0c\n\x04nome\x18\x02 \x01(\t\x12\x11\n\tprofessor\x18\x03 \x01(\t\x12\x11\n\tcod_curso\x18\x04 \x01(\x05\"l\n\tMatricula\x12\n\n\x02RA\x18\x01 \x01(\x05\x12\x16\n\x0e\x63od_disciplina\x18\x02 \x01(\t\x12\x0b\n\x03\x61no\x18\x03 \x01(\x05\x12\x10\n\x08semestre\x18\x04 \x01(\x05\x12\x0c\n\x04nota\x18\x05 \x01(\x02\x12\x0e\n\x06\x66\x61ltas\x18\x06 \x01(\x05\"E\n\x05\x41luno\x12\n\n\x02RA\x18\x01 \x01(\x05\x12\x0c\n\x04nome\x18\x02 \x01(\t\x12\x0f\n\x07periodo\x18\x03 \x01(\x05\x12\x11\n\tcod_curso\x18\x04 \x01(\x05\x62\x06proto3')



_TYPEMESSAGE = DESCRIPTOR.message_types_by_name['TypeMessage']
_MSGREPLY = DESCRIPTOR.message_types_by_name['MsgReply']
_NUMCHAIR = DESCRIPTOR.message_types_by_name['NumChair']
_CURSO = DESCRIPTOR.message_types_by_name['Curso']
_DISCIPLINA = DESCRIPTOR.message_types_by_name['Disciplina']
_MATRICULA = DESCRIPTOR.message_types_by_name['Matricula']
_ALUNO = DESCRIPTOR.message_types_by_name['Aluno']
TypeMessage = _reflection.GeneratedProtocolMessageType('TypeMessage', (_message.Message,), {
  'DESCRIPTOR' : _TYPEMESSAGE,
  '__module__' : 'noteManagement_pb2'
  # @@protoc_insertion_point(class_scope:TypeMessage)
  })
_sym_db.RegisterMessage(TypeMessage)

MsgReply = _reflection.GeneratedProtocolMessageType('MsgReply', (_message.Message,), {
  'DESCRIPTOR' : _MSGREPLY,
  '__module__' : 'noteManagement_pb2'
  # @@protoc_insertion_point(class_scope:MsgReply)
  })
_sym_db.RegisterMessage(MsgReply)

NumChair = _reflection.GeneratedProtocolMessageType('NumChair', (_message.Message,), {
  'DESCRIPTOR' : _NUMCHAIR,
  '__module__' : 'noteManagement_pb2'
  # @@protoc_insertion_point(class_scope:NumChair)
  })
_sym_db.RegisterMessage(NumChair)

Curso = _reflection.GeneratedProtocolMessageType('Curso', (_message.Message,), {
  'DESCRIPTOR' : _CURSO,
  '__module__' : 'noteManagement_pb2'
  # @@protoc_insertion_point(class_scope:Curso)
  })
_sym_db.RegisterMessage(Curso)

Disciplina = _reflection.GeneratedProtocolMessageType('Disciplina', (_message.Message,), {
  'DESCRIPTOR' : _DISCIPLINA,
  '__module__' : 'noteManagement_pb2'
  # @@protoc_insertion_point(class_scope:Disciplina)
  })
_sym_db.RegisterMessage(Disciplina)

Matricula = _reflection.GeneratedProtocolMessageType('Matricula', (_message.Message,), {
  'DESCRIPTOR' : _MATRICULA,
  '__module__' : 'noteManagement_pb2'
  # @@protoc_insertion_point(class_scope:Matricula)
  })
_sym_db.RegisterMessage(Matricula)

Aluno = _reflection.GeneratedProtocolMessageType('Aluno', (_message.Message,), {
  'DESCRIPTOR' : _ALUNO,
  '__module__' : 'noteManagement_pb2'
  # @@protoc_insertion_point(class_scope:Aluno)
  })
_sym_db.RegisterMessage(Aluno)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TYPEMESSAGE._serialized_start=24
  _TYPEMESSAGE._serialized_end=51
  _MSGREPLY._serialized_start=53
  _MSGREPLY._serialized_end=80
  _NUMCHAIR._serialized_start=82
  _NUMCHAIR._serialized_end=110
  _CURSO._serialized_start=112
  _CURSO._serialized_end=149
  _DISCIPLINA._serialized_start=151
  _DISCIPLINA._serialized_end=231
  _MATRICULA._serialized_start=233
  _MATRICULA._serialized_end=341
  _ALUNO._serialized_start=343
  _ALUNO._serialized_end=412
# @@protoc_insertion_point(module_scope)
